import type { Metadata } from "next";

import { LegalPageShell } from "@/components/legal-page-shell";
import { getSupportEmail } from "@/lib/site-contact";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How CrazyLoops handles account, workflow, submission, and execution data.",
  alternates: { canonical: "https://www.crazy-loops.com/privacy" },
};

export default function PrivacyPage() {
  const supportEmail = getSupportEmail();
  return (
    <LegalPageShell eyebrow="Privacy" title="Privacy Policy" description="How CrazyLoops handles information and the controls available to account holders.">
      <section><h2>Who operates CrazyLoops</h2><p className="mt-3">CrazyLoops operates this service. For privacy questions or help with your account data, contact <a href={`mailto:${supportEmail}`}>{supportEmail}</a>.</p></section>
      <section><h2>Information we handle</h2><ul className="mt-3"><li>Account email, Auth identity metadata, and session cookies needed to sign in.</li><li>Workflow prompts, configuration, immutable versions, public-form settings, and publication status.</li><li>Public-form submissions, execution inputs and outputs, step history, status, timing, and sanitized provider metadata.</li><li>When an account holder connects Google, the selected Google account identity, granted-scope metadata, Gmail message text and metadata needed by configured triggers, and Google Sheets headers or cell values needed by configured actions. Gmail attachments are initially retained as metadata references only and are not downloaded automatically.</li><li>When an account holder connects Slack or Notion, the selected workspace identity, permission metadata, configured channel or resource identifiers, Slack message data required by enabled triggers/actions, and Notion page or data-source fields required by enabled workflows.</li><li>Generated PDF documents and private document metadata.</li><li>Connector credential ciphertext and metadata. Credential values are encrypted before storage and are not included in account exports.</li><li>Usage counters and pseudonymous security signals used for rate limiting, concurrency control, fraud prevention, and reliability.</li></ul></section>
      <section><h2>How information is used</h2><p className="mt-3">We use this information to authenticate users, save and run requested automations, show execution history, generate documents, enforce limits, diagnose failures, prevent abuse, and provide account export or deletion controls. A public submission is processed according to the workflow owner’s configured and published workflow.</p></section>
      <section><h2>AI processing</h2><p className="mt-3">When—and only when—a workflow contains an enabled AI capability, relevant workflow instructions and input may be sent server-side to the configured AI provider. Current production AI processing uses Groq. AI output can be inaccurate and should be reviewed before important use. See <a href="/data-use">AI &amp; Data Use</a>.</p></section>
      <section><h2>Google data and permissions</h2><p className="mt-3">CrazyLoops requests Google permissions incrementally for the Gmail or Google Sheets operation the account holder chooses. Relevant Google workflow data may be sent to the configured AI provider only when the workflow includes an enabled AI step. Google data is not used for unrelated advertising or to train a general-purpose CrazyLoops model. See <a href="/data-use">AI &amp; Data Use</a> for access, token storage, retention, disconnection, and deletion details.</p></section>
      <section><h2>Infrastructure and service providers</h2><p className="mt-3">CrazyLoops currently relies on Vercel for application hosting, Supabase for authentication, database, and private object storage, Groq for configured AI execution, Cloudflare Turnstile for bot protection, Google APIs when an account holder connects Gmail or Google Sheets, Slack APIs when Slack is connected, and Notion APIs when Notion is connected. These providers process information under their own terms and policies.</p></section>
      <section><h2>Cookies and browser storage</h2><p className="mt-3">Supabase Auth uses cookies to maintain an authenticated session. CrazyLoops may use browser storage for non-secret workflow interface state; historical browser entries are cleared on logout and account deletion. Credentials and elevated service keys are not intentionally stored in browser storage.</p></section>
      <section><h2>Retention, export, and deletion</h2><p className="mt-3">Account data is kept while it is needed to provide and protect the service or until the account holder removes it. Account settings provide a bounded JSON export and self-service deletion. Deletion first disables public forms, then removes account-owned workflow data, credential records, generated documents, usage records, and the Auth identity. Limited security and operational records may remain temporarily where needed for abuse prevention, reliability, or legal obligations.</p></section>
      <section><h2>Security and choices</h2><p className="mt-3">CrazyLoops uses account-scoped authorization, row-level database controls where applicable, encrypted credential storage, private document storage, expiring signed links, CAPTCHA, rate limits, and execution safeguards. No online service can promise absolute security. You can export or delete your data in Settings.</p></section>
      <section><h2>Contact</h2><p className="mt-3">For privacy, export, or deletion help, contact <a href={`mailto:${supportEmail}`}>{supportEmail}</a>.</p></section>
    </LegalPageShell>
  );
}
